# Generated by Django 5.2.12 on 2026-03-09 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('source_type', models.CharField(choices=[('news', 'News'), ('twitter', 'Twitter'), ('reddit', 'Reddit'), ('website', 'Website'), ('telegram', 'Telegram')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('confidence_score', models.FloatField(default=0.5)),
                ('analyst_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.rawdata')),
            ],
        ),
        migrations.AddField(
            model_name='rawdata',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.source'),
        ),
    ]
