# Generated by Django 5.2.12 on 2026-03-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
