# Generated by Django 5.2.12 on 2026-03-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_alter_rawdata_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencereport',
            name='category',
            field=models.CharField(choices=[('energia', 'Energía'), ('financiero', 'Financiero'), ('regulatorio', 'Regulatorio'), ('consumo_masivo', 'Consumo Masivo'), ('reputacional', 'Reputacional'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
