# Generated by Django 5.2.12 on 2026-03-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_intelligencereport_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='category',
            field=models.CharField(choices=[('energia', 'Energía'), ('financiero', 'Financiero'), ('regulatorio', 'Regulatorio'), ('politica', 'Política'), ('economia', 'Economía'), ('consumo_masivo', 'Consumo Masivo'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
