# Generated by Django 5.2.12 on 2026-03-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0004_rawdata_published_at_source_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='category',
            field=models.CharField(choices=[('energia', 'Energía'), ('financiero', 'Financiero'), ('regulatorio', 'Regulatorio'), ('politica', 'Política'), ('economia', 'Economía'), ('mundo', 'Mundo / Internacional'), ('consumo_masivo', 'Consumo Masivo'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
