# Generated by Django 5.2.12 on 2026-03-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0005_alter_source_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
