# Generated by Django 5.2.12 on 2026-03-31 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0006_rawdata_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('label', models.CharField(choices=[('PER', 'Persona'), ('ORG', 'Organización'), ('LOC', 'Lugar'), ('MISC', 'Miscelánea'), ('DATE', 'Fecha'), ('MONEY', 'Dinero/Cantidad')], max_length=10)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('news_appearance_count', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['-news_appearance_count', '-last_seen'],
                'unique_together': {('normalized_name', 'label')},
            },
        ),
        migrations.CreateModel(
            name='EntityMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('context', models.TextField(blank=True)),
                ('position', models.CharField(choices=[('title', 'Título'), ('body', 'Cuerpo'), ('both', 'Ambos')], default='body', max_length=20)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positivo'), ('negative', 'Negativo'), ('neutral', 'Neutral')], max_length=10, null=True)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='intelligence.entity')),
                ('raw_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_mentions', to='intelligence.rawdata')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('entity', 'raw_data')},
            },
        ),
    ]
